"""Added department field to User model

Revision ID: 244cdbce061b
Revises: 299d83df5b41
Create Date: 2025-03-19 16:35:34.387911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244cdbce061b'
down_revision = '299d83df5b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
