"""Updated models with relationships

Revision ID: 713965411b1d
Revises: 04e219e50516
Create Date: 2025-03-23 16:49:09.249156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713965411b1d'
down_revision = '04e219e50516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('meeting_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
